version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=shopuser
      - POSTGRES_PASSWORD=devpass
  web:
    image: yuliya2001/myshop
    command: bash -c "
      python shop/manage.py migrate &&
      python shop/manage.py loaddata shop/db.json &&
      python shop/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always



