# Generated by Django 3.2.4 on 2021-06-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('max_loading', models.CharField(max_length=255, verbose_name='Максимальный объем загрузки')),
                ('max_spin_speed', models.CharField(max_length=255, verbose_name='Максимальная скорость отжима')),
                ('number_of_programs', models.CharField(max_length=255, verbose_name='Количество программ стирки')),
                ('shortest_program', models.CharField(max_length=255, verbose_name='Время самой короткой программы')),
                ('electricity_consumption_per_cycle', models.CharField(max_length=255, verbose_name='Расход электроэнергии за цикл')),
                ('water_consumption_per_cycle', models.CharField(max_length=255, verbose_name='Расход воды за цикл')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefrigeratorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('overall_volume', models.CharField(max_length=255, verbose_name='Общий объем')),
                ('useful_volume', models.CharField(max_length=255, verbose_name='Полезный объем')),
                ('noise_level', models.CharField(max_length=255, verbose_name='Тип управления')),
                ('control', models.CharField(max_length=255, verbose_name='Уровень шума')),
                ('number_of_shelves', models.CharField(max_length=255, verbose_name='Количество полок')),
                ('number_of_freezer_shelves', models.CharField(max_length=255, verbose_name='Количество полок морозильной камеры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
