# Generated by Django 3.2.4 on 2021-06-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_refrigeratorproduct_washerproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefrigeratorProduct',
            new_name='Refrigerator',
        ),
        migrations.RenameModel(
            old_name='WasherProduct',
            new_name='Washer',
        ),
    ]
