# Generated by Django 3.2.4 on 2021-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210606_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerator',
            name='control',
            field=models.CharField(max_length=255, verbose_name='Тип управления'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='noise_level',
            field=models.CharField(max_length=255, verbose_name='Уровень шума'),
        ),
    ]
