# Generated by Django 3.2.4 on 2021-06-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_dishwasher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishwasher',
            name='drying',
            field=models.BooleanField(default=True, verbose_name='Наличие сушки'),
        ),
        migrations.AlterField(
            model_name='dishwasher',
            name='drying_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип сушки'),
        ),
    ]
