# Generated by Django 3.2.4 on 2021-06-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210607_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishwasher',
            name='child_lock',
            field=models.BooleanField(default=True, verbose_name='Блокировка от детей'),
        ),
    ]
